SET SERVEROUTPUT ON;

DECLARE
    CURSOR EXP_CUR IS SELECT RNO,SNAME,MAR FROM ST_M;
    TMP ST_M%ROWTYPE;
BEGIN
    
    OPEN EXP_CUR;
    LOOP
        EXIT WHEN EXP_CUR % NOTFOUND;
        FETCH EXP_CUR INTO TMP;
        DBMS_OUTPUT.PUT_LINE('ROLL : '|| TMP.RNO || 'NAME : '|| TMP.SNAME|| 'MARKS : '|| TMP.MAR);
    END LOOP;
    
    IF EXP_CUR%ROWCOUNT > 0 THEN
        DBMS_OUTPUT.PUT_LINE(EXP_CUR%ROWCOUNT ||' ROWS FOUND');
    ELSE    
        DBMS_OUTPUT.PUT_LINE('RECORD NOT PRESENT');
    END IF;
    CLOSE EXP_CUR;
END;