SET SERVEROUTPUT ON;

BEGIN
    UPDATE ST_M SET SNAME = 'XYZ' WHERE RNO = 2;
    IF SQL % FOUND THEN
        DBMS_OUTPUT.PUT_LINE('UPDATED');
    END IF;
    IF SQL % NOTFOUND THEN
        DBMS_OUTPUT.PUT_LINE('NOT FOUND');
    END IF;
    IF SQL % ROWCOUNT > 0 THEN
        DBMS_OUTPUT.PUT_LINE(SQL % ROWCOUNT || ' ROWS UPDATED');
    END IF;
END;    